Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -73,23 +73,27 @@ jobs:
         run: |
           echo "Running tests..."
           ctest --build-config "${{ matrix.build_type }}"
-          
+
       - name: Run Benchmark 
         shell: bash
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         run: |
           echo "Running benchmark tests..."
           if [[ "$RUNNER_OS" == "Windows_NT" ]]; then
-          if [ -d "Release" ]; then
-          cd Release
-          echo "Changed directory to Release"
+            if [ -d "Release" ]; then
+              cd Release
+              echo "Changed directory to Release"
+            fi
           fi
-          benchmark_cmd="matrix_benchmark.exe"
-          else
+          if [ -f "matrix_benchmark.exe" ]; then
+            benchmark_cmd="matrix_benchmark.exe"
+          elif [ -f "matrix_benchmark" ]; then
             benchmark_cmd="./matrix_benchmark"
+          else
+            echo "Error: matrix_benchmark executable not found!"
+            exit 1
           fi
           echo "Executing: $benchmark_cmd --size 3000 --iterations 10"
           $benchmark_cmd --size 3000 --iterations 10 > benchmark_output.txt
           echo "Benchmark output:"
           cat benchmark_output.txt
-
